security:
  encryption:
    token-expiration-time-millis: '604800000'
    key: 2A472D4B6150645367566B59703273357638792F423F4528482B4D6251655468
pdf:
  fonts:
    directory: ${DOCKER_FONTS_DIRECTORY} #src/main/resources/fonts/

    classic: DejaVuSans.ttf
    bold: DejaVuSans-Bold.ttf
    size: '10'
    title_size: '20'
    subtitle_size: '16'
    encoding: cp1251
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    #    hikari:
    #      jdbcUrl: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/BusinessService}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
  flyway:
    enabled: false
  liquibase:
    enabled: ${SPRING_ENABLE_LIQUIBASE}
    drop-first: ${SPRING_ENABLE_LIQUIBASE_DROP_FIRST}
    default-schema: public
server:
  error:
    include-binding-errors: always
    include-message: always
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
